apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-api-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: POSTGRES_PASSWORD
