apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.app.port }}
  type: NodePort
    