apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-api-secret
  namespace: student-api
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: student-api-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: student-api
        property: POSTGRES_PASSWORD