apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: student-api       # same namespace as your app
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      # vault = service name
      # vault = namespace vault is running in
      # 8200  = vault's port
      path: "secret"           # the KV mount name (from vault kv list)
      version: "v2"            # dev mode always uses v2
      auth:
        tokenSecretRef:
            name: vault-token          # name of the K8s secret holding token {kubectl create secret generic vault-token \--from-literal=VAULT_TOKEN=root \-n student-api}
            key: VAULT_TOKEN           # key inside that K8s secret
