Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "student-api-server"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.provider :utm do |utm|
        utm.name = "student-api-server"
        utm.memory = 2048
        utm.cpus = 2
    end
    config.vm.provision "shell", path: "scripts/setup.sh"
end