apiVersion: v1
kind: ConfigMap
metadata:
  name: student-api-config
  namespace: student-api
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "students_db"
  DB_USER: "postgres"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api-deployment
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      nodeSelector:
        type: application
      containers:
      - name: student-api
        image: jayanthkundrapu/student-api:v1.0.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: student-api-config  
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-api-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://postgres:$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  namespace: student-api
spec:
  selector:
    app: student-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
  