apiVersion: v1
kind: Secret
metadata:
  name: student-crud-api-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository   # ← tells ArgoCD this is a repo secret
type: Opaque
stringData:
  type: git
  url: https://github.com/JayanthNaiduKundrapu/student-crud-api
  # for public repos, username and password are optional
  # for private repos add:
  # username: your-github-username
  # password: your-github-pat-token
