services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - python-app-api-1
      - python-app-api-2
    networks:
      - student-network
  python-app-api-1:
    build: . 
    container_name: api1
    expose:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/students_db
      - POSTGRES_HOST=db 
    networks:
      - student-network
    depends_on:
    - db
  python-app-api-2:
    build: .
    container_name: api2
    expose:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/students_db
      - POSTGRES_HOST=db
    networks:
      - student-network
    depends_on:
    - db
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=students_db
    ports:
      - "5432:5432"
    networks:
      - student-network
networks:
  student-network:
    driver: bridge