events {}
http {
    upstream student-api {
        server python-app-api-1:5000;
        server python-app-api-2:5000;
    }


    server {
        listen 80;

        location / {
            proxy_pass http://student-api;
        }
    }
}
